# Site settings
title: Ryan Liang's Blog
description: >
  A blog for tracking Ryan's coding progress

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ryanliang.com" # the base hostname & protocol for your site

author:
  fullname: Ryan Liang
  github: ryanliang
  twitter: ryanliang
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile