# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Orangeball
tagline:          'Work Hard!  Stay Relevant!'
description:      'Some writing about programming'
url:              
baseurl:          /

author:
  name:           'Ryan Liang'
  url:            https://twitter.com/ryanliang

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ryanliang
