#title in header
title: "Hi There."

#main info
#owner
owner: "I am Ryan Liang"
#email: firstnamelastname@gmail.com
info: "An experienced developer based in Toronto, Canada"
#description
desc: "This is my personal blog, a private space documenting my coding journey!"

#menu
menu:
  CV: /cv
  About: /about

#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Toronto
placelink: https://en.wikipedia.org/wiki/Toronto
github: https://github.com/ryanliang
linkedin: https://www.linkedin.com/in/zhichengliang/
#twitter: https://twitter.com/adisaktijrs

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: na

theme:
  placename: minima